-- ============================================================================
-- LOOK Restobar -- seed data v2, rebuilt directly from the venue's official
-- "Meniu Sala" PDF (Aug 2026 edition) -- names, prices, weights and dish
-- photography all verified against that source. Run once, after schema.sql,
-- on a FRESH (empty) database.
--
-- Idempotent by design: each block only inserts when its table is still
-- empty, so running this again after the admin has edited, added or deleted
-- anything never overwrites or duplicates their work.
--
-- Already have live data that needs to match this update? Don't run this
-- file -- run supabase/menu_refresh_2026.sql instead, which replaces
-- everything in place (see docs/ADMIN.md).
-- ============================================================================

insert into public.menu_categories (slug, name, icon, sort_order, translations, emoji)
select * from (values
  ('gustari', 'Gustări', 'bread', 0, '{"ru":{"name":"Закуски"},"en":{"name":"Starters"}}'::jsonb, "🥗"),
  ('salate', 'Salate', 'leaf', 10, '{"ru":{"name":"Салаты"},"en":{"name":"Salads"}}'::jsonb, "🥬"),
  ('supe', 'Supe', 'bowl', 20, '{"ru":{"name":"Супы"},"en":{"name":"Soups"}}'::jsonb, "🍲"),
  ('paste', 'Paste', 'noodle', 30, '{"ru":{"name":"Паста"},"en":{"name":"Pasta"}}'::jsonb, "🍝"),
  ('peste', 'Pește & Fructe de mare', 'fish', 40, '{"ru":{"name":"Рыба и морепродукты"},"en":{"name":"Fish & Seafood"}}'::jsonb, "🐟"),
  ('carne', 'Carne & Grătar', 'meat', 50, '{"ru":{"name":"Мясо и гриль"},"en":{"name":"Meat & Grill"}}'::jsonb, "🥩"),
  ('burgeri', 'Burgeri', 'burger', 60, '{"ru":{"name":"Бургеры"},"en":{"name":"Burgers"}}'::jsonb, "🍔"),
  ('platouri', 'Platouri pentru masă', 'platter', 70, '{"ru":{"name":"Блюда на компанию"},"en":{"name":"Sharing Platters"}}'::jsonb, "🍽️"),
  ('garnituri', 'Garnituri', 'fries', 80, '{"ru":{"name":"Гарниры"},"en":{"name":"Sides"}}'::jsonb, "🍟"),
  ('deserturi', 'Deserturi', 'cake', 90, '{"ru":{"name":"Десерты"},"en":{"name":"Desserts"}}'::jsonb, "🍰")
) as seed(slug, name, icon, sort_order, translations, emoji)
where not exists (select 1 from public.menu_categories);

insert into public.menu_items (category_id, name, description, price, weight, photo_url, signature, sort_order, translations)
select mc.id, seed.name, seed.description, seed.price, seed.weight, seed.photo_url, seed.signature, seed.sort_order, seed.translations
from (values
  ('gustari', 'Vitello Tonnato', 'Mușchiuleț de vită, mix de salată, sparanghel, capere, roșii cherry coapte, sos tonnato, ulei de trufe.', 200, '280 g', '/dish-photos/vittello-tonnato.jpg', false, 0, '{"ru": {"name": "Вителло Тоннато", "description": "Вырезка говядины, микс салата, спаржа, каперсы, запечённые томаты черри, соус тоннато, трюфельное масло."}, "en": {"name": "Vitello Tonnato", "description": "Beef tenderloin, salad mix, asparagus, capers, roasted cherry tomatoes, tonnato sauce, truffle oil."}}'::jsonb),
  ('gustari', 'Vânătă cu sos Parmigiano', 'Vânătă, roșii cherry coapte, sos parmigiano.', 135, '300 g', '/dish-photos/vanata-parmigiano.jpg', false, 10, '{"ru": {"name": "Баклажан с соусом пармиджано", "description": "Баклажан, запечённые томаты черри, соус пармиджано."}, "en": {"name": "Eggplant with Parmigiano Sauce", "description": "Eggplant, roasted cherry tomatoes, Parmigiano sauce."}}'::jsonb),
  ('gustari', 'Ardei copt cu sos tonnato', 'Ardei copt, sos tonnato, ciabatta.', 105, '300 g', '/dish-photos/ardei-copt-tonnato.jpg', false, 20, '{"ru": {"name": "Печёный перец с соусом тоннато", "description": "Печёный перец, соус тоннато, чиабатта."}, "en": {"name": "Roasted Pepper with Tonnato Sauce", "description": "Roasted pepper, tonnato sauce, ciabatta."}}'::jsonb),
  ('gustari', 'Tartar de ton', 'Ton, avocado, castraveți, caviar roșu, fulgi de ton, ceapă crocantă, sos de susan, chuka.', 200, '250 g', '/dish-photos/tartar-ton.jpg', true, 30, '{"ru": {"name": "Тартар из тунца", "description": "Тунец, авокадо, огурцы, красная икра, хлопья тунца, хрустящий лук, кунжутный соус, чука."}, "en": {"name": "Tuna Tartare", "description": "Tuna, avocado, cucumber, red caviar, tuna flakes, crispy onion, sesame sauce, chuka salad."}}'::jsonb),
  ('gustari', 'Tartar de somon', 'Somon, avocado, castraveți, caviar roșu, perle din orez, chips din crab, sos de susan.', 190, '250 g', '/dish-photos/tartar-somon.jpg', false, 40, '{"ru": {"name": "Тартар из лосося", "description": "Лосось, авокадо, огурцы, красная икра, рисовые жемчужины, крабовые чипсы, кунжутный соус."}, "en": {"name": "Salmon Tartare", "description": "Salmon, avocado, cucumber, red caviar, rice pearls, crab chips, sesame sauce."}}'::jsonb),
  ('gustari', 'Bruschetta cu somon', 'Ciabatta, cremă de cașcaval, somon s/s, ulei verde, castraveți, semințe de susan.', 120, '150 g', '/dish-photos/bruschetta-somon.jpg', false, 50, '{"ru": {"name": "Брускетта с лососем", "description": "Чиабатта, сырный крем, слабосолёный лосось, зелёное масло, огурцы, кунжут."}, "en": {"name": "Salmon Bruschetta", "description": "Ciabatta, cheese cream, cured salmon, herb oil, cucumber, sesame seeds."}}'::jsonb),
  ('gustari', 'Bruschetta cu roast beef', 'Ciabatta, sos tonnato, roast beef, capere, cremă balsamică, cașcaval Parmigiano, semințe de susan.', 100, '150 g', '/dish-photos/bruschetta-roastbeef.jpg', false, 60, '{"ru": {"name": "Брускетта с ростбифом", "description": "Чиабатта, соус тоннато, ростбиф, каперсы, бальзамический крем, пармиджано, кунжут."}, "en": {"name": "Roast Beef Bruschetta", "description": "Ciabatta, tonnato sauce, roast beef, capers, balsamic cream, Parmigiano, sesame seeds."}}'::jsonb),
  ('gustari', 'Bruschetta cu roșii cherry', 'Ciabatta, sos bulgăresc, roșii cherry coapte, sos pesto, spanac, ulei verde.', 85, '150 g', '/dish-photos/bruschetta-rosii-chery.jpg', false, 70, '{"ru": {"name": "Брускетта с томатами черри", "description": "Чиабатта, болгарский соус, запечённые томаты черри, соус песто, шпинат, зелёное масло."}, "en": {"name": "Cherry Tomato Bruschetta", "description": "Ciabatta, Bulgarian-style sauce, roasted cherry tomatoes, pesto, spinach, herb oil."}}'::jsonb),
  ('gustari', 'Asorti de bruschete', 'Bruschetă cu somon, bruschetă cu roast beef, bruschetă cu roșii cherry.', 260, '450 g', '/dish-photos/asorti-bruschete.jpg', false, 80, '{"ru": {"name": "Ассорти брускетт", "description": "Брускетта с лососем, брускетта с ростбифом, брускетта с томатами черри."}, "en": {"name": "Bruschetta Assortment", "description": "Salmon bruschetta, roast beef bruschetta, cherry tomato bruschetta."}}'::jsonb),
  ('gustari', 'Midii pane', 'Carne de midii, tempura, sos de soia, usturoi, sos spicy, lămâie.', 180, '250 g', '/dish-photos/midii-pane.jpg', false, 90, '{"ru": {"name": "Мидии в панировке", "description": "Мясо мидий, темпура, соевый соус, чеснок, острый соус, лимон."}, "en": {"name": "Breaded Mussels", "description": "Mussel meat, tempura batter, soy sauce, garlic, spicy sauce, lemon."}}'::jsonb),
  ('gustari', 'Creveți pane', 'Creveți, tempura, panco, usturoi, sos spicy, lămâie.', 390, '850 g', '/dish-photos/creveti-pane.jpg', false, 100, '{"ru": {"name": "Креветки в панировке", "description": "Креветки, темпура, панко, чеснок, острый соус, лимон."}, "en": {"name": "Breaded Shrimp", "description": "Shrimp, tempura batter, panko, garlic, spicy sauce, lemon."}}'::jsonb),
  ('gustari', 'Calmar pane', 'Calmar, panco, ou, sos spicy, lămâie.', 180, '250 g', '/dish-photos/calmar-pane.jpg', false, 110, '{"ru": {"name": "Кальмар в панировке", "description": "Кальмар, панко, яйцо, острый соус, лимон."}, "en": {"name": "Breaded Calamari", "description": "Calamari, panko, egg, spicy sauce, lemon."}}'::jsonb),
  ('gustari', 'Crispy SeaFood', 'Carne de midii, tempura, sos de soia, usturoi, sos spicy, lămâie, creveți pane.', 550, '850 g', '/dish-photos/crispy-seafood.jpg', true, 120, '{"ru": {"name": "Крисп сифуд", "description": "Мясо мидий, темпура, соевый соус, чеснок, острый соус, лимон, креветки в панировке."}, "en": {"name": "Crispy Seafood", "description": "Mussel meat, tempura batter, soy sauce, garlic, spicy sauce, lemon, breaded shrimp."}}'::jsonb),
  ('gustari', 'Antipasti crudo', 'Salamuri italiene, olive, măsline, gressini.', 270, '380 g', '/dish-photos/antipasti-crudo.jpg', false, 130, '{"ru": {"name": "Антипасти крудо", "description": "Итальянские колбасы, оливки, маслины, гриссини."}, "en": {"name": "Antipasti Crudo", "description": "Italian cured meats, green and black olives, grissini."}}'::jsonb),
  ('salate', 'Salata cu creveți și mango', 'Mix de salată, creveți, mango, avocado, dressing de portocală.', 170, '280 g', '/dish-photos/salata-creveti-mango.jpg', false, 0, '{"ru": {"name": "Салат с креветками и манго", "description": "Микс салата, креветки, манго, авокадо, апельсиновая заправка."}, "en": {"name": "Shrimp & Mango Salad", "description": "Salad mix, shrimp, mango, avocado, orange dressing."}}'::jsonb),
  ('salate', 'Salata cu ton', 'Mix salată, ton, roșii cherry coapte, măsline, ou de prepeliță, sos sesame, semințe de susan.', 190, '270 g', '/dish-photos/salata-ton.jpg', false, 10, '{"ru": {"name": "Салат с тунцом", "description": "Микс салата, тунец, запечённые томаты черри, маслины, перепелиное яйцо, кунжутный соус, кунжут."}, "en": {"name": "Tuna Salad", "description": "Salad mix, tuna, roasted cherry tomatoes, olives, quail egg, sesame dressing, sesame seeds."}}'::jsonb),
  ('salate', 'Salata cu somon', 'Mix de salată, somon s/s, castravete, avocado, roșii cherry coapte, sos de susan, semințe de susan.', 160, '280 g', '/dish-photos/salata-somon.jpg', false, 20, '{"ru": {"name": "Салат с лососем", "description": "Микс салата, слабосолёный лосось, огурец, авокадо, запечённые томаты черри, кунжутный соус, кунжут."}, "en": {"name": "Salmon Salad", "description": "Salad mix, cured salmon, cucumber, avocado, roasted cherry tomatoes, sesame dressing, sesame seeds."}}'::jsonb),
  ('salate', 'Salata cu calmar și mango', 'Mix de salată, tentacule de calmar, mango, avocado, dressing de portocală.', 170, '280 g', '/dish-photos/salata-calmar-mango.jpg', false, 30, '{"ru": {"name": "Салат с кальмаром и манго", "description": "Микс салата, щупальца кальмара, манго, авокадо, апельсиновая заправка."}, "en": {"name": "Calamari & Mango Salad", "description": "Salad mix, calamari tentacles, mango, avocado, orange dressing."}}'::jsonb),
  ('salate', 'Salata cu vită fragedă și vinete', 'Mix de salată, carne de vită fragedă, ciuperci, ardei copți, vinete, sos de miere și muștar, semințe de susan.', 150, '400 g', '/dish-photos/salata-vita-fragede-vinete.jpg', false, 40, '{"ru": {"name": "Салат с нежной говядиной и баклажаном", "description": "Микс салата, нежная говядина, грибы, печёный перец, баклажан, медово-горчичный соус, кунжут."}, "en": {"name": "Tender Beef & Eggplant Salad", "description": "Salad mix, tender beef, mushrooms, roasted pepper, eggplant, honey-mustard sauce, sesame seeds."}}'::jsonb),
  ('salate', 'Salata Caesar cu creveți', 'Mix de salată Iceberg, sos Caesar, creveți, usturoi, roșii cherry, crutoane, cașcaval Parmigiano.', 150, '450 g', '/dish-photos/salata-caesar-creveti.jpg', false, 50, '{"ru": {"name": "Салат Цезарь с креветками", "description": "Салат Айсберг, соус Цезарь, креветки, чеснок, томаты черри, крутоны, пармиджано."}, "en": {"name": "Caesar Salad with Shrimp", "description": "Iceberg lettuce, Caesar dressing, shrimp, garlic, cherry tomatoes, croutons, Parmigiano."}}'::jsonb),
  ('salate', 'Salata Caesar cu pui', 'Mix de salată Iceberg, file de pui pane, roșii cherry, crutoane, sos Caesar, ou de prepeliță, cașcaval Parmigiano.', 140, '340 g', '/dish-photos/salata-caesar-pui.jpg', false, 60, '{"ru": {"name": "Салат Цезарь с курицей", "description": "Салат Айсберг, куриное филе в панировке, томаты черри, крутоны, соус Цезарь, перепелиное яйцо, пармиджано."}, "en": {"name": "Caesar Salad with Chicken", "description": "Iceberg lettuce, breaded chicken fillet, cherry tomatoes, croutons, Caesar dressing, quail egg, Parmigiano."}}'::jsonb),
  ('salate', 'Salata Greek Garden', 'Mix de salată, roșii cherry, ardei, castraveți, ceapă roșie, măsline, brânză bulgărească, dressing.', 110, '320 g', '/dish-photos/salata-greek-garden.jpg', false, 70, '{"ru": {"name": "Салат Грик Гарден", "description": "Микс салата, томаты черри, перец, огурцы, красный лук, маслины, болгарская брынза, заправка."}, "en": {"name": "Greek Garden Salad", "description": "Salad mix, cherry tomatoes, bell pepper, cucumber, red onion, olives, Bulgarian cheese, dressing."}}'::jsonb),
  ('supe', 'Borș roșu', 'Costiță de porc, legume, slănină condimentată, usturoi, smântână, ardei iute, pâine neagră.', 95, '680 g', '/dish-photos/bors-rosu.jpg', false, 0, '{"ru": {"name": "Борщ красный", "description": "Свиные рёбрышки, овощи, приправленное сало, чеснок, сметана, острый перец, чёрный хлеб."}, "en": {"name": "Red Borscht", "description": "Pork ribs, vegetables, seasoned lard, garlic, sour cream, hot pepper, black bread."}}'::jsonb),
  ('supe', 'Zeamă', 'Carne de pui, morcov, ardei gras, roșii, tăiței de casă, verdeață, smântână, ardei iute.', 75, '460 g', '/dish-photos/zeama.jpg', false, 10, '{"ru": {"name": "Дзама (куриный суп)", "description": "Курица, морковь, болгарский перец, томаты, домашняя лапша, зелень, сметана, острый перец."}, "en": {"name": "Zeamă (Chicken Soup)", "description": "Chicken, carrot, bell pepper, tomato, homemade noodles, herbs, sour cream, hot pepper."}}'::jsonb),
  ('supe', 'Tom Yam', 'Lapte de cocos, pastă Tom Yam, creveți, ciuperci, roșii cherry, verdeață, orez chinezesc.', 120, '400 g', '/dish-photos/tom-yam.jpg', false, 20, '{"ru": {"name": "Том Ям", "description": "Кокосовое молоко, паста том-ям, креветки, грибы, томаты черри, зелень, рис."}, "en": {"name": "Tom Yum", "description": "Coconut milk, Tom Yum paste, shrimp, mushrooms, cherry tomatoes, herbs, rice."}}'::jsonb),
  ('supe', 'Supă de cașcaval cu creveți', 'Legume, cașcaval Cheddar, creveți, cașcaval Parmigiano, semințe de susan.', 120, '450 g', '/dish-photos/supa-cascaval-creveti.jpg', false, 30, '{"ru": {"name": "Сырный суп с креветками", "description": "Овощи, сыр Чеддер, креветки, пармиджано, кунжут."}, "en": {"name": "Cheese Soup with Shrimp", "description": "Vegetables, Cheddar cheese, shrimp, Parmigiano, sesame seeds."}}'::jsonb),
  ('paste', 'Paste cu fructe de mare', 'Paste, tentacule de calmar, creveți, midii de Marea Neagră, carne de midii, usturoi, unt, vin alb, roșii cherry.', 220, '400 g', '/dish-photos/paste-fructe-de-mare.jpg', true, 0, '{"ru": {"name": "Паста с морепродуктами", "description": "Паста, щупальца кальмара, креветки, черноморские мидии, мясо мидий, чеснок, сливочное масло, белое вино, томаты черри."}, "en": {"name": "Seafood Pasta", "description": "Pasta, calamari tentacles, shrimp, Black Sea mussels, mussel meat, garlic, butter, white wine, cherry tomatoes."}}'::jsonb),
  ('paste', 'Spaghetti alla Carbonara', 'Spaghetti, pancetta, ou, cașcaval Parmigiano.', 150, '360 g', '/dish-photos/spaghetti-carbonara.jpg', false, 10, '{"ru": {"name": "Спагетти Карбонара", "description": "Спагетти, панчетта, яйцо, пармиджано."}, "en": {"name": "Spaghetti alla Carbonara", "description": "Spaghetti, pancetta, egg, Parmigiano."}}'::jsonb),
  ('paste', 'Paste cu beef', 'Paste, mușchiuleț de vită, roșii cherry, pulpă de roșii, busuioc, usturoi, cașcaval Parmigiano.', 170, '400 g', '/dish-photos/paste-cu-beef.jpg', false, 20, '{"ru": {"name": "Паста с говядиной", "description": "Паста, вырезка говядины, томаты черри, томатная мякоть, базилик, чеснок, пармиджано."}, "en": {"name": "Beef Pasta", "description": "Pasta, beef tenderloin, cherry tomatoes, tomato pulp, basil, garlic, Parmigiano."}}'::jsonb),
  ('peste', 'Dorado cu legume baby', 'File de dorado, legume baby, boabe edamame, unt, sos de capere.', 290, '370 g', '/dish-photos/dorado-legume-baby.jpg', false, 0, '{"ru": {"name": "Дорадо с молодыми овощами", "description": "Филе дорадо, молодые овощи, эдамаме, сливочное масло, соус из каперсов."}, "en": {"name": "Dorado with Baby Vegetables", "description": "Dorado fillet, baby vegetables, edamame beans, butter, caper sauce."}}'::jsonb),
  ('peste', 'Somon cu sparanghel', 'Somon, sparanghel, zucchini, sos Parmigiano.', 320, '350 g', '/dish-photos/somon-sparanghel.jpg', false, 10, '{"ru": {"name": "Лосось со спаржей", "description": "Лосось, спаржа, цукини, соус пармиджано."}, "en": {"name": "Salmon with Asparagus", "description": "Salmon, asparagus, zucchini, Parmigiano sauce."}}'::jsonb),
  ('peste', 'Fructe de mare', 'Tentacule de calmar, creveți, midii de Marea Neagră, midii cu carne, roșii cherry, usturoi, unt, cimbru, vin alb, ciabatta.', 300, '360 g', '/dish-photos/fructe-de-mare.jpg', true, 20, '{"ru": {"name": "Морепродукты", "description": "Щупальца кальмара, креветки, черноморские мидии, мидии с мясом, томаты черри, чеснок, сливочное масло, тимьян, белое вино, чиабатта."}, "en": {"name": "Seafood Platter", "description": "Calamari tentacles, shrimp, Black Sea mussels, mussel meat, cherry tomatoes, garlic, butter, thyme, white wine, ciabatta."}}'::jsonb),
  ('carne', 'File mignon cu sparanghel', 'Mușchiuleț de vită, sparanghel, cartof baby, usturoi, unt, cimbru, sos demi-glace.', 350, '450 g', '/dish-photos/file-mignon-sparanghel.jpg', true, 0, '{"ru": {"name": "Филе миньон со спаржей", "description": "Вырезка говядины, спаржа, молодой картофель, чеснок, сливочное масло, тимьян, соус демигласс."}, "en": {"name": "Filet Mignon with Asparagus", "description": "Beef tenderloin, asparagus, baby potatoes, garlic, butter, thyme, demi-glace sauce."}}'::jsonb),
  ('carne', 'Steak New York', 'Cartof baby, usturoi, unt, cimbru, sos demi-glace.', 450, '500 g', '/dish-photos/steak-new-york.jpg', false, 10, '{"ru": {"name": "Стейк Нью-Йорк", "description": "Молодой картофель, чеснок, сливочное масло, тимьян, соус демигласс."}, "en": {"name": "New York Steak", "description": "Baby potatoes, garlic, butter, thyme, demi-glace sauce."}}'::jsonb),
  ('carne', 'Steak Cowboy', 'Cartof baby, usturoi, unt, cimbru, sos demi-glace.', 750, '850 g', '/dish-photos/steak-cowboy.jpg', true, 20, '{"ru": {"name": "Стейк Ковбой", "description": "Молодой картофель, чеснок, сливочное масло, тимьян, соус демигласс."}, "en": {"name": "Cowboy Steak", "description": "Baby potatoes, garlic, butter, thyme, demi-glace sauce."}}'::jsonb),
  ('carne', 'Medalion de porc cu cartof baby', 'Mușchiuleț de porc, cartof baby, ciuperci, usturoi, unt, cimbru, sos demi-glace.', 250, '470 g', '/dish-photos/medalion-porc-cartof-baby.jpg', false, 30, '{"ru": {"name": "Медальоны из свинины с молодым картофелем", "description": "Свиная вырезка, молодой картофель, грибы, чеснок, сливочное масло, тимьян, соус демигласс."}, "en": {"name": "Pork Medallions with Baby Potatoes", "description": "Pork tenderloin, baby potatoes, mushrooms, garlic, butter, thyme, demi-glace sauce."}}'::jsonb),
  ('carne', 'Miel cu legume', 'Carne de miel cu os, legume baby, sos demi-glace, roșii cherry, usturoi, unt, cimbru.', 370, '500 g', '/dish-photos/miel-cu-legume.jpg', false, 40, '{"ru": {"name": "Ягнёнок с овощами", "description": "Мясо ягнёнка на кости, молодые овощи, соус демигласс, томаты черри, чеснок, сливочное масло, тимьян."}, "en": {"name": "Lamb with Vegetables", "description": "Bone-in lamb, baby vegetables, demi-glace sauce, cherry tomatoes, garlic, butter, thyme."}}'::jsonb),
  ('carne', 'Steak de pui cu legume', 'Piept de pui, legume baby, unt, sos Dor Blue.', 170, '400 g', '/dish-photos/steak-pui-cu-legume.jpg', false, 50, '{"ru": {"name": "Куриный стейк с овощами", "description": "Куриная грудка, молодые овощи, сливочное масло, соус Дор Блю."}, "en": {"name": "Chicken Steak with Vegetables", "description": "Chicken breast, baby vegetables, butter, Dor Blue cheese sauce."}}'::jsonb),
  ('carne', 'File de rață cu piure de cartof', 'File de rață, piure de cartof, sos de vișine.', 280, '500 g', '/dish-photos/file-rata-pireu-batat.jpg', false, 60, '{"ru": {"name": "Филе утки с картофельным пюре", "description": "Филе утки, картофельное пюре, вишнёвый соус."}, "en": {"name": "Duck Fillet with Mashed Potatoes", "description": "Duck fillet, mashed potatoes, cherry sauce."}}'::jsonb),
  ('burgeri', 'Burger American cu carne maturată și sos BBQ', 'Chiflă crocantă, carne maturată, roșii, cașcaval, castraveți murați, ceapă roșie, cartofi prăjiți, sos BBQ, ketchup.', 170, '470 g', null, false, 0, '{"ru": {"name": "Бургер Американ с выдержанной говядиной и соусом BBQ", "description": "Хрустящая булочка, выдержанная говядина, томаты, сыр, маринованные огурцы, красный лук, картофель фри, соус BBQ, кетчуп."}, "en": {"name": "American Burger with Aged Beef & BBQ Sauce", "description": "Crispy bun, aged beef patty, tomato, cheese, pickles, red onion, fries, BBQ sauce, ketchup."}}'::jsonb),
  ('burgeri', 'Burger Krispy cu file de pui', 'Chiflă crocantă, salată verde, piept de pui pane, Cheddar, roșii, cartofi prăjiți, ketchup.', 150, '370 g', null, false, 10, '{"ru": {"name": "Бургер Криспи с куриным филе", "description": "Хрустящая булочка, листья салата, куриное филе в панировке, чеддер, томаты, картофель фри, кетчуп."}, "en": {"name": "Krispy Chicken Burger", "description": "Crispy bun, lettuce, breaded chicken fillet, Cheddar, tomato, fries, ketchup."}}'::jsonb),
  ('burgeri', 'Burger BBQ Smash din coastă ruptă', 'Chiflă crocantă, carne de porc ruptă, salată coleslaw, roșii, sos BBQ, cartofi prăjiți, ketchup.', 170, '500 g', null, false, 20, '{"ru": {"name": "Бургер BBQ Смэш из тушёных рёбер", "description": "Хрустящая булочка, рваная свинина, салат коулслоу, томаты, соус BBQ, картофель фри, кетчуп."}, "en": {"name": "BBQ Smash Burger with Pulled Pork Ribs", "description": "Crispy bun, pulled pork, coleslaw, tomato, BBQ sauce, fries, ketchup."}}'::jsonb),
  ('platouri', 'Platou Grand Steakhouse', 'Steak Cowboy, steak New York, steak Chateaubriand, cartofi copți, roșii cherry, legume grill, sos de trufe, sos demi-glace.', 1500, '2000 g', '/dish-photos/platou-grand-steakhouse.jpg', true, 0, '{"ru": {"name": "Платтер Гранд Стейкхаус", "description": "Стейк Ковбой, стейк Нью-Йорк, стейк Шатобриан, печёный картофель, томаты черри, овощи гриль, трюфельный соус, соус демигласс."}, "en": {"name": "Grand Steakhouse Platter", "description": "Cowboy steak, New York steak, Chateaubriand steak, baked potatoes, cherry tomatoes, grilled vegetables, truffle sauce, demi-glace sauce."}}'::jsonb),
  ('platouri', 'Platou Delicatesele Mării', 'Tentacule de calmar, creveți pane, midii de Marea Neagră, ton pane, file de dorado, somon, cartofi baby, broccoli, lămâie, sos spicy.', 1600, '2000 g', '/dish-photos/platou-delicatesele-marii.jpg', true, 10, '{"ru": {"name": "Платтер Дары Моря", "description": "Щупальца кальмара, креветки в панировке, черноморские мидии, тунец в панировке, филе дорадо, лосось, молодой картофель, брокколи, лимон, острый соус."}, "en": {"name": "Sea Delicacies Platter", "description": "Calamari tentacles, breaded shrimp, Black Sea mussels, breaded tuna, dorado fillet, salmon, baby potatoes, broccoli, lemon, spicy sauce."}}'::jsonb),
  ('platouri', 'Platou de carne', 'Piept de pui la grătar, mușchi de vită, mușchiuleț de porc, cartof baby, roșii cherry, legume la grătar, sos de trufe, sos demi-glace.', 1300, '2000 g', '/dish-photos/platou-de-carne.jpg', false, 20, '{"ru": {"name": "Мясной платтер", "description": "Куриная грудка на гриле, говяжья вырезка, свиная вырезка, молодой картофель, томаты черри, овощи гриль, трюфельный соус, соус демигласс."}, "en": {"name": "Meat Platter", "description": "Grilled chicken breast, beef tenderloin, pork tenderloin, baby potatoes, cherry tomatoes, grilled vegetables, truffle sauce, demi-glace sauce."}}'::jsonb),
  ('platouri', 'Platou de brânzeturi', 'Cașcavaluri Dor Blue, brie, Parmigiano, ementaler, struguri, fructe de sezon, miere de albine.', 270, '450 g', '/dish-photos/platou-branzeturi.jpg', false, 30, '{"ru": {"name": "Сырный платтер", "description": "Дор Блю, бри, пармиджано, эмменталь, виноград, сезонные фрукты, мёд."}, "en": {"name": "Cheese Platter", "description": "Dor Blue, brie, Parmigiano, Emmental, grapes, seasonal fruit, honey."}}'::jsonb),
  ('platouri', 'Antipasti de lux', 'Cașcavaluri Dor Blue, brie, Parmigiano, ementaler, struguri, fructe de sezon, miere de albine, salamuri italiene, măsline, pere, miez de nuci, gressini.', 990, '1700 g', null, true, 40, '{"ru": {"name": "Антипасти Люкс", "description": "Дор Блю, бри, пармиджано, эмменталь, виноград, сезонные фрукты, мёд, итальянские колбасы, маслины, груши, ядра грецкого ореха, гриссини."}, "en": {"name": "Deluxe Antipasti", "description": "Dor Blue, brie, Parmigiano, Emmental, grapes, seasonal fruit, honey, Italian cured meats, olives, pears, walnuts, grissini."}}'::jsonb),
  ('platouri', 'Platou de fructe', 'Selecție de fructe de sezon.', 250, '800 g', null, false, 50, '{"ru": {"name": "Фруктовый платтер", "description": "Ассорти сезонных фруктов."}, "en": {"name": "Fruit Platter", "description": "A selection of seasonal fruit."}}'::jsonb),
  ('garnituri', 'Coș cu pâine', 'Selecție de pâine proaspătă de casă.', 30, null, null, false, 0, '{"ru": {"name": "Корзинка с хлебом", "description": "Ассорти свежего домашнего хлеба."}, "en": {"name": "Bread Basket", "description": "A selection of fresh house-made bread."}}'::jsonb),
  ('garnituri', 'Baghetă cu unt și usturoi', 'Baghetă crocantă, unt aromat cu usturoi.', 40, null, null, false, 10, '{"ru": {"name": "Багет с чесночным маслом", "description": "Хрустящий багет, ароматное масло с чесноком."}, "en": {"name": "Garlic Butter Baguette", "description": "Crispy baguette with fragrant garlic butter."}}'::jsonb),
  ('garnituri', 'Cartofi baby', 'Cartof baby copt cu ierburi aromate.', 70, '300 g', '/dish-photos/cartofi-baby.jpg', false, 20, '{"ru": {"name": "Молодой картофель", "description": "Печёный молодой картофель с ароматными травами."}, "en": {"name": "Baby Potatoes", "description": "Roasted baby potatoes with aromatic herbs."}}'::jsonb),
  ('garnituri', 'Legume grill', 'Selecție de legume la grătar.', 85, '350 g', '/dish-photos/legume-grill.jpg', false, 30, '{"ru": {"name": "Овощи гриль", "description": "Ассорти овощей на гриле."}, "en": {"name": "Grilled Vegetables", "description": "A selection of grilled vegetables."}}'::jsonb),
  ('garnituri', 'Sparanghel', 'Sparanghel proaspăt.', 120, '100 g', '/dish-photos/sparanghel.jpg', false, 40, '{"ru": {"name": "Спаржа", "description": "Свежая спаржа."}, "en": {"name": "Asparagus", "description": "Fresh asparagus."}}'::jsonb),
  ('deserturi', 'Cheesecake San Sebastian, ciocolată/caramel', 'Cheesecake ars în stil San Sebastian.', 100, null, '/dish-photos/chescake-ciocolata-caramela.jpg', false, 0, '{"ru": {"name": "Чизкейк Сан-Себастьян, шоколад/карамель", "description": "Обожжённый чизкейк в стиле Сан-Себастьян."}, "en": {"name": "San Sebastián Cheesecake, Chocolate/Caramel", "description": "Burnt cheesecake in San Sebastián style."}}'::jsonb),
  ('deserturi', 'Cheesecake San Sebastian, mango & maracuja', 'Cheesecake ars în stil San Sebastian.', 135, null, '/dish-photos/chescake-mango-maracuja.jpg', false, 10, '{"ru": {"name": "Чизкейк Сан-Себастьян, манго и маракуйя", "description": "Обожжённый чизкейк в стиле Сан-Себастьян."}, "en": {"name": "San Sebastián Cheesecake, Mango & Passion Fruit", "description": "Burnt cheesecake in San Sebastián style."}}'::jsonb),
  ('deserturi', 'Cheesecake Rafaello', 'Cheesecake cu note de cocos și migdale.', 95, null, '/dish-photos/cheesecake-rafaelo.jpg', false, 20, '{"ru": {"name": "Чизкейк Рафаэлло", "description": "Чизкейк с нотками кокоса и миндаля."}, "en": {"name": "Raffaello Cheesecake", "description": "Cheesecake with coconut and almond notes."}}'::jsonb),
  ('deserturi', 'Tiramisu', 'Clasicul desert italian cu mascarpone și cafea.', 95, null, '/dish-photos/tiramisu.jpg', false, 30, '{"ru": {"name": "Тирамису", "description": "Классический итальянский десерт с маскарпоне и кофе."}, "en": {"name": "Tiramisu", "description": "The classic Italian dessert with mascarpone and coffee."}}'::jsonb),
  ('deserturi', 'Mango', 'Variantă de desert cu mango.', 110, null, '/dish-photos/mango-desert.jpg', false, 40, '{"ru": {"name": "Манго", "description": "Десерт с манго."}, "en": {"name": "Mango", "description": "A mango-based dessert."}}'::jsonb),
  ('deserturi', 'Boabă de cafea', 'Variantă de desert cu aromă de cafea.', 110, null, '/dish-photos/boaba-de-cafea.jpg', false, 50, '{"ru": {"name": "Кофейное зерно", "description": "Десерт с кофейным ароматом."}, "en": {"name": "Coffee Bean", "description": "A coffee-flavored dessert."}}'::jsonb),
  ('deserturi', 'Zmeură', 'Variantă de desert cu zmeură.', 110, null, '/dish-photos/zmeura.jpg', false, 60, '{"ru": {"name": "Малина", "description": "Десерт с малиной."}, "en": {"name": "Raspberry", "description": "A raspberry-based dessert."}}'::jsonb)
) as seed(category_slug, name, description, price, weight, photo_url, signature, sort_order, translations)
join public.menu_categories mc on mc.slug = seed.category_slug
where not exists (select 1 from public.menu_items);
